version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "lifecycleaware/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "lifecycleaware/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew lint ktlintCheck test
      - store_artifacts:
          path: lifecycleaware/build/reports
          destination: reports
      - store_test_results:
          path: lifecycleaware/build/test-results

      - run:
          command: gem update --system 2.4.8
          when: always
      - run:
          command: gem install bundler
          when: always
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle install --path vendor/bundle
          when: always
      - save_cache:
          paths: vendor/bundle
          key: gems-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle exec danger
          when: always
